version: '3.2'

services:
  app:
    build: ./
    volumes:
    - ./:/web
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=development
    depends_on:
     - db

  db:
    image: mongo:latest
    
